from repofix.agents.fix_agent import FixAgent
from repofix.agents.repository_agent import RepositoryAgent
from repofix.github.pull_request import PullRequestService
from repofix.models import FixAttempt, Issue, Repository
from repofix.db.database import SessionLocal
from repofix.services.repository_service import RepositoryService


class FixWorkflow:
    def __init__(self) -> None:
        self.repository_service = RepositoryService()
        self.repository_agent = RepositoryAgent()
        self.fix_agent = FixAgent()
        self.pull_request_service = PullRequestService()

    def run(
        self,
        repository: Repository,
        issue: Issue,
        workspace_path: str,
        branch_name: str,
    ) -> dict:
        db = SessionLocal()
        # 1. Clone repository
        repository_path = (
            self.repository_service.clone_repository(
                repository,
                workspace_path,
            )
        )

        # 2. Create isolated fix branch
        self.repository_service.create_fix_branch(
            repository_path,
            branch_name,
        )

        # 3. Analyze issue, retrieve relevant files,
        #    and run static analysis
        analysis = self.repository_agent.analyze_issue(
            repository_path=repository_path,
            title=issue.title,
            description=issue.description,
        )

        # 4. Generate patch, apply patch, run tests,
        #    validate, and retry when necessary
        fix_result = self.fix_agent.run(
            repository_path=repository_path,
            issue_title=issue.title,
            issue_description=issue.description or "",
            relevant_files=analysis["relevant_files"],
            static_analysis=analysis["static_analysis"],
            reasoning=analysis["reasoning"],
        )

        for attempt in fix_result["attempts"]:
            db_attempt = FixAttempt(
                issue_id=issue.id,
                attempt_number=attempt["attempt"],
                status=attempt["status"],
                patch=attempt.get("patch"),
                test_output=attempt.get("test_output"),
                error_message=attempt.get("error"),
            )
            db.add(db_attempt)

        db.commit()
        db.close()
        # 5. Stop if the fix was not validated
        if not fix_result["success"]:
            return {
                "success": False,
                "stage": "validation",
                "result": fix_result,
            }

        # 6. Commit validated fix
        commit_sha = self.repository_service.commit_fix(
            repository_path,
            f"fix: resolve issue #{issue.number}",
        )

        # 7. Push fix branch
        self.repository_service.push_branch(
            repository_path,
            branch_name,
        )

        # 8. Create GitHub Pull Request
        pull_request = (
            self.pull_request_service.create_pull_request(
                repository_name=repository.full_name,
                branch_name=branch_name,
                issue_number=issue.number,
                title=f"fix: resolve issue #{issue.number}",
                body=(
                    "Automated fix generated by RepoFix AI "
                    f"for GitHub issue #{issue.number}."
                ),
            )
        )

        return {
            "success": True,
            "repository_path": repository_path,
            "branch": branch_name,
            "commit_sha": commit_sha,
            "pull_request": pull_request,
            "fix_result": fix_result,
        }